const List<String> kSupportedCurrencies = [
  'USD',
  'EUR',
  'GBP',
  'CHF',
  'JPY',
  'CAD',
  'AUD',
  'HKD',
  'SEK',
  'NOK',
  'DKK',
];

const Map<String, String> kExchangeToCurrencyMap = {
  'XETRA': 'EUR',
  'Milan': 'EUR',
  'Stockholm': 'SEK',
  'London': 'GBP',
  'Stuttgart': 'EUR',
  'Swiss': 'CHF',
  'Paris': 'EUR',
  'NYSE': 'USD',
  'NASDAQ': 'USD',
  'Toronto': 'CAD',
  'Amsterdam': 'EUR',
  'Frankfurt': 'EUR',
  'Madrid': 'EUR',
  'Oslo': 'NOK',
  'Copenhagen': 'DKK',
  'Helsinki': 'EUR',
  'Tokyo': 'JPY',
  'Hong Kong': 'HKD',
  'Sydney': 'AUD',
};

const Map<String, String> kSymbolSuffixToCurrencyMap = {
  '.L': 'GBP',
  '.MI': 'EUR',
  '.DE': 'EUR',
  '.F': 'EUR',
  '.SG': 'EUR',
  '.MU': 'EUR',
  '.HM': 'EUR',
  '.PA': 'EUR',
  '.AS': 'EUR',
  '.MA': 'EUR',
  '.SW': 'CHF',
  '.TO': 'CAD',
  '.AX': 'AUD',
  '.T': 'JPY',
  '.HK': 'HKD',
};
